### ISSUE TITLE
PHP 5.4 requirement breaks composer install on older server

### ISSUE THREAD

**Issue by fmarangi** [EcomDev/SUPEE6788-PerformanceFix#6]
See [here](https://github.com/EcomDev/SUPEE6788-PerformanceFix/blob/master/composer.json#L7), I went through your code and honestly couldn't find anything which is not PHP 5.3.\* compliant. Of course we are not running 5.3 on production, but we have an older server where we are testing some stuff and the requirement breaks the installation. Is it really necessary? Can it be removed or downgraded? I know Magento claim they require 5.4, but it's actually still running smoothly on 5.3.

**Comment by IvanChepurnyi** [comment]
Short array syntax is not 5.3 compatible. As well 5.3 is not secure anyomre, as it reached a EOL a long time ago, so I advice to move to 5.4, there is not that much things that break, espcially if you apply core 5.4 patch to make older 1.x version work on 5.4.
